openapi: 3.0.3
info:
  title: Trade Logger - OpenAPI 3.0
  description: A simple trade log
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://xxxx/api/v3
tags:
  - name: trade
    description: Everything about your trades
    externalDocs:
      description: Find out more
      url: http://swagger.io
paths:
  /trade/{tradeId}:
    get:
      tags:
        - trade
      summary: Find trade by ID
      description: Returns a single trade
      operationId: gettradeById
      parameters:
        - name: tradeId
          in: path
          description: ID of trade to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/trade'
              examples:
                'buy ':
                  value: |-
                    {
                      "id": 10,
                      "ticker": "NFLX",
                      "status": "bought"
                    }
                'sell':
                  value: |-
                    {
                      "id": 11,
                      "ticker": "NFLX",
                      "status": "sold"
                    }
            application/xml:
              schema:
                $ref: '#/components/schemas/trade'
        '400':
          description: Invalid ID supplied
        '404':
          description: trade not found
components:
  schemas:
    trade:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        ticker:
          type: string
          example: NFLX
        status:
          type: string
          description: trade status in the store
          enum:
            - bought
            - sold
  requestBodies:
    trade:
      description: trade object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/trade'
        application/xml:
          schema:
            $ref: '#/components/schemas/trade'
